AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31' 

Globals:
  Function:
    Timeout: 5

Resources:
  SimpleFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
    MemorySize: 3008
      FunctionName: SimpleFunction
      Handler: notes.handler
      Runtime: nodejs16.x
      Events:
        GetAll:
          Type: HttpApi
          Properties:
            Path: /notes
            Method: GET

Outputs:
  ApiEndpoint:
    Description: "The invoke URL for our HTTP API"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
