AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  samLocalStackFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: samLocalStackFunction
      Handler: notes.handler
      Runtime: nodejs16.x
      Events:
        GetAll:
          Type: HttpApi
          Properties:
            Path: /notes
            Method: GET
